version: '3'
services:
  server-cp:
    image: rancher/k3s:latest
    command: server
    tmpfs:
    - /run
    - /var/run
    privileged: true
    environment:
    - K3S_CLUSTER_SECRET=clustersecret-cp
    - K3S_KUBECONFIG_OUTPUT=/output/kubeconfig-cp.yaml
    - K3S_KUBECONFIG_MODE=666
    volumes:
    - k3s-server-cp:/var/lib/rancher/k3s
    # This is just so that we get the kubeconfig file out
    - .:/output
    ports:
    - 6443:6443

  node-cp:
    image: rancher/k3s:latest
    tmpfs:
    - /run
    - /var/run
    privileged: true
    depends_on:
    - server-cp
    environment:
    - K3S_URL=https://server-cp:6443
    - K3S_CLUSTER_SECRET=clustersecret-cp
    ports:
    - 21090-21091:31090
    - 21190-21191:31190
    - 21300-21301:31300

  server-cc:
    image: rancher/k3s:latest
    command: server
    tmpfs:
    - /run
    - /var/run
    privileged: true
    environment:
    - K3S_CLUSTER_SECRET=clustersecret-cc
    - K3S_KUBECONFIG_OUTPUT=/output/kubeconfig-cc.yaml
    - K3S_KUBECONFIG_MODE=666
    volumes:
    - k3s-server-cc:/var/lib/rancher/k3s
    # This is just so that we get the kubeconfig file out
    - .:/output
    ports:
    - 6444:6443

  node-cc:
    image: rancher/k3s:latest
    tmpfs:
    - /run
    - /var/run
    privileged: true
    depends_on:
    - server-cc
    environment:
    - K3S_URL=https://server-cc:6443
    - K3S_CLUSTER_SECRET=clustersecret-cc
    ports:
    - 22090-22091:31090
    - 22190-22191:31190

  store-s3:
    image: minio/minio:latest
    #networks:
    #  - store
    environment:
      - "MINIO_ACCESS_KEY=admin"
      - "MINIO_SECRET_KEY=admin123"
    entrypoint: sh
    #TODO check if this works for more than one prometheus
    # This is a workaround for creating the bucket "thanosbucket"
    #command: -c 'mkdir -p /data/bucket001 && mkdir -p /data/bucket002 && mkdir -p /data/bucket003 && /usr/bin/minio server /data'
    command: -c 'mkdir -p /data/bucket001 && mkdir -p /data/bucket002 && /usr/bin/minio server /data'
    volumes:
      - store-s3:/data
    ports:
    - 19000:9000

volumes:
  k3s-server-cp: {}
  k3s-server-cc: {}
  store-s3: {}
