apiVersion: apps/v1beta2
kind: Deployment
metadata:
  labels:
    app: thanos-query
  name: thanos-query
  namespace: monitoring
spec:
  replicas: 2
  selector:
    matchLabels:
      app: thanos-query
  template:
    metadata:
      labels:
        app: thanos-query
    spec:
      containers:
      - args:
        - query
        - --log.level=debug
        - --query.timeout=2m
        - --query.max-concurrent=20
        - --query.replica-label=replica
        - --query.auto-downsampling
        - --store=dnssrv+thanos-store-gateway.monitoring.svc
        - --store.sd-dns-interval=30s
        - --store.sd-files=store-targets-sd.json
        - --store.sd-interval=1m
        image: improbable/thanos:v0.6.0
        name: thanos-query
        ports:
        - containerPort: 10902
          name: http
        - containerPort: 10901
          name: grpc
        livenessProbe:
          httpGet:
            path: /-/healthy
            port: http
        volumeMounts:
        - name: config-store-sd
          mountPath: "/store-targets-sd.json"
          subPath: "store-targets-sd.json"
      volumes:
      - name: config-store-sd
        configMap:
          name: thanos-query-store-sd
