apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  labels:
    release: test
    k8s-app: thanos-store
  name: thanos-store
  namespace: monitoring
spec:
  endpoints:
  - interval: 15s
    port: http
  jobLabel: k8s-app
  selector:
    matchLabels:
      app: thanos-store
