apiVersion: v1
kind: Service
metadata:
  labels:
    thanos-peers: "true"
  name: thanos-peers
  namespace: monitoring
spec:
  clusterIP: None
  ports:
  - name: cluster
    port: 10900
    targetPort: cluster
  - name: http
    port: 10902
    targetPort: http
  selector:
    thanos-peers: "true"
  type: ClusterIP
