apiVersion: v1
kind: Service
metadata:
  labels:
    app: thanos-query
  name: thanos-query
  namespace: monitoring
spec:
  type: NodePort
  ports:
  - name: http
    port: 9090
    nodePort: 31190
    targetPort: http
  selector:
    app: thanos-query