---

commonLabels:
  group: test

defaultRules:
  rules:
    alertmanager: true

alertmanager:
  enabled: true

grafana:
  enabled: true
  adminUser: admin
  adminPassword: admin123
  datasources:
    datasources.yaml:
      apiVersion: 1
      #deleteDatasources:
      #- name: Prometheus
      #  orgId: 1
      datasources:
      - name: Prometheus
        isDefault: false
      - name: Thanos
        type: prometheus
        access: proxy
        orgId: 1
        url: http://thanos-query:9090
        #isDefault: true
  service:
    type: NodePort
    port: 80
    targetPort: 3000
    nodePort: 31300

kubeApiServer:
  enabled: true

kubelet:
  enabled: true

kubeControllerManager:
  enabled: true

coreDns:
  enabled: true

kubeEtcd:
  enabled: true

kubeScheduler:
  enabled: true

kubeStateMetrics:
  enabled: true

nodeExporter:
  enabled: true

prometheusOperator:
  service:
    ## Additional ports to open for Prometheus service
    ## ref: https://kubernetes.io/docs/concepts/services-networking/service/#multi-port-services
    ##
    additionalPorts: []
    #  - name: thanos-cluster
    #    port: 10900
    #    nodePort: 30111
  createCustomResource: false

prometheus:
  enabled: true
  service:
    targetPort: 9090
    nodePort: 31090
    type: NodePort
  rbac:
    # note: a role binding in the release namespace will always be created
    roleNamespaces:
      - kube-system
  prometheusSpec:
    #scrapeInterval: ""
    #evaluationInterval: ""
    externalLabels:
      customer: none
    retention: 3h
    replicas: 1
    podMetadata:
      labels:
        app: thanos-sidecar
        thanos-store-api: "true"
    remoteRead: {}
    remoteWrite: {}
    additionalScrapeConfigs: []
    #additionalScrapeConfigs:
    #  - job_name: 'federate'
    #    scrape_interval: 15s
    #    honor_labels: true
    #    metrics_path: '/federate'
    #    params:
    #      'match[]':
    #        - '{job="kube-state-metrics"}'
    #        - '{__name__=~"job:.*"}'
    #    static_configs:
    #      - targets:
    #        - 'to-be-overwritten-prometheus-1:9090'
    #        - 'to-be-overwritten-prometheus-2:9090'
    ## Thanos configuration allows configuring various aspects of a Prometheus server in a Thanos environment.
    ## This section is experimental, it may change significantly without deprecation notice in any release.
    ## This is experimental and may change significantly without backward compatibility in any release.
    ## ref: https://github.com/coreos/prometheus-operator/blob/master/Documentation/api.md#thanosspec
    ##
    # add the Thanos sidecar to the Prometheus Pod, see also: https://github.com/coreos/prometheus-operator/blob/master/Documentation/api.md#thanosspec
    thanos:
      baseImage: improbable/thanos
      version: v0.5.0
      objectStorageConfig:
        key: thanos.yaml
        name: thanos-objstore-config
