apiVersion: v1
kind: ConfigMap
metadata:
  labels:
    app: thanos-query
  name: thanos-query-store-sd
  namespace: monitoring
data:
  store-targets-sd.json: |-
    [
      {
        "targets": [${store-targets-sd}]
      }
    ]
