# derived from https://github.com/m-kraus/prometheus_experiments/blob/master/thanos/creds/bucket_config.s3-minio.sample
type: S3
config:
  access_key: "admin"
  secret_key: "admin123"
  bucket: "bucket001"
  endpoint: "${store-s3-ip}:9000"
  insecure: true
  signature_version2: true
  encrypt_sse: false
  put_user_metadata: {}
  http_config:
    idle_conn_timeout: 0s
    insecure_skip_verify: false
